openapi: 3.0.0
info:
  title: locale API
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /signup:
    post:
      tags:
        - default
      summary: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: enose
                last_name: felix
                email: enosefelix@gmail.com
                password: Enose2001
                retype_password: Enose2001
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: verify
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: enosefelix@gmail.com
                password: Enose2001
                API_key: '#_4WbO+NcpCDRu4r9ePC!IXvcvJr%9PK'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /location:
    get:
      tags:
        - default
      summary: get all locations
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /location/state:
    get:
      tags:
        - default
      summary: get by state
      parameters:
        - name: lga
          in: query
          schema:
            type: boolean
          example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /location/region/:
    get:
      tags:
        - default
      summary: get by region
      security:
        - bearerAuth: []
      parameters:
        - name: lga
          in: query
          schema:
            type: boolean
          example: 'true'
        - name: region_name
          in: query
          schema:
            type: string
          example: south south
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /location/lga:
    get:
      tags:
        - default
      summary: get by local government
      security:
        - bearerAuth: []
      parameters:
        - name: lga_name
          in: query
          schema:
            type: string
          example: esanu
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
